/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package com.huaweicloud.cs.scala.v1.model

import com.huaweicloud.cs.scala.v1.client.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class JobDetailEntity (
  /* 作业ID */
  jobId: Option[Long],
  /* 作业名称 */
  name: Option[String],
  /* 作业描述 */
  desc: Option[String],
  /* 作业类型 */
  jobType: Option[String],
  /* 作业状态 */
  status: Option[String],
  /* 作业状态描述 */
  statusDesc: Option[String],
  /* 作业创建时间 */
  createTime: Option[Long],
  /* 作业启动时间, 0尚未启动 */
  startTime: Option[Long],
  /* 作业所属用户标识 */
  userId: Option[String],
  /* 预留的集群资源ID, 当前用户有该预留资源的使用权限 */
  clusterId: Option[Long],
  /* 作业所属项目标识 */
  projectId: Option[String],
  /* Stream SQL语句 */
  sqlBody: Option[String],
  /* 作业运行模式，共享或者独享模式 */
  runMode: Option[JobDetailEntityEnums.RunMode],
  /* 用户为作业选择的SPU数量 */
  spuNumber: Option[Int],
  /* 用户设置的作业并行数 */
  parallelNumber: Option[Int],
  jobConfig: Option[JobConfig],
  /* jar包的OBS路径 */
  jarUrl: Option[String],
  /* checkpoint_enabled==true是, 用户授权保存快照的OBS路径 */
  mainClass: Option[String],
  /* jar包作业运行参数 */
  args: Option[String],
  /* 作业执行计划 */
  executionGraph: Option[String],
  /* 作业更新时间 */
  updateTime: Option[Long]
) extends ApiModel

object JobDetailEntityEnums {

  type RunMode = RunMode.Value
  object RunMode extends Enumeration {
    val SharedCluster = Value("shared_cluster")
    val ExclusiveCluster = Value("exclusive_cluster")
  }

}

