/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package com.huaweicloud.cs.scala.v1.model

import com.huaweicloud.cs.scala.v1.client.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class UserQuotaInfo (
  /* 用户ID */
  userId: Option[String],
  /* 用户名称 */
  userName: Option[String],
  /* 用户已使用SPU配额 */
  spuUsed: Option[Int],
  /* 用户最大SPU配额 */
  spuQuota: Option[Int],
  /* 用户可使用的集群列表 */
  clusters: Option[Seq[UserCluster]]
) extends ApiModel


