/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 */
package com.huaweicloud.cs.v1

import com.huaweicloud.cs.v1.client._
import com.huaweicloud.cs.v1.model.{GlobalErrorResponse, JobAuditLog}

object LogApi {

  /**
   *
   *
   * Expected answers:
   * code 200 : Seq[JobAuditLog] (审计日志列表查询成功)
   * code 400 : GlobalErrorResponse (无效的输入参数)
   *
   * @param xProjectId project id, 用于不同project取token.
   * @param resourceType 资源类型，包括job、template和cluster
   * @param cursor 作业ID游标
   * @param resourceId 资源ID
   * @param pageNumber 查询的页码
   * @param limit 查询条数限制
   */
  def getJobAuditLogs(xProjectId: String, resourceType: String, cursor: Option[String] = None, resourceId: Option[String] = None, pageNumber: Option[Int], limit: Option[Int] = None): ApiRequest[Seq[JobAuditLog]] =
    ApiRequest[Seq[JobAuditLog]](ApiMethods.GET, "https://cs.cn-north-1.myhuaweicloud.com/v1.0", "/{X-Project-Id}/audit_logs", "application/json")
      .withQueryParam("resource_type", resourceType)
      .withQueryParam("cursor", cursor)
      .withQueryParam("resource_id", resourceId)
      .withQueryParam("page_number", pageNumber)
      .withQueryParam("limit", limit)
      .withPathParam("X-Project-Id", xProjectId)
      .withSuccessResponse[Seq[JobAuditLog]](200)
      .withErrorResponse[GlobalErrorResponse](400)


}

