/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 */
package com.huaweicloud.cs.v1

import com.huaweicloud.cs.v1.client._
import com.huaweicloud.cs.v1.model.{GlobalErrorResponse, OverviewResponse}

object StatisticsApi {

  /**
   *
   * Expected answers:
   * code 200 : OverviewResponse (查询概要统计信息成功)
   * code 400 : GlobalErrorResponse (无效的输入参数)
   *
   * @param xProjectId project id, 用于不同project取token.
   */
  def overview(xProjectId: String): ApiRequest[OverviewResponse] =
    ApiRequest[OverviewResponse](ApiMethods.GET, "https://cs.cn-north-1.myhuaweicloud.com/v1.0", "/{X-Project-Id}/overview", "application/json")
      .withPathParam("X-Project-Id", xProjectId)
      .withSuccessResponse[OverviewResponse](200)
      .withErrorResponse[GlobalErrorResponse](400)


}

