/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 */
package com.huaweicloud.cs.v1

import com.huaweicloud.cs.v1.client._
import com.huaweicloud.cs.v1.model.{GlobalErrorResponse, JobTemplate, JobTemplateRequest}

object TemplateApi {

  /**
   * Create on job template from CloudStream Service
   *
   * Expected answers:
   * code 200 : Boolean (创建作业模板成功)
   * code 400 : GlobalErrorResponse (无效的输入参数)
   *
   * @param xProjectId project id, 用于不同project取token.
   * @param body Create job template request
   */
  def createJobTemplate(xProjectId: String, body: JobTemplateRequest): ApiRequest[Boolean] =
    ApiRequest[Boolean](ApiMethods.POST, "https://cs.cn-north-1.myhuaweicloud.com/v1.0", "/{X-Project-Id}/job_template", "application/json")
      .withBody(body)
      .withPathParam("X-Project-Id", xProjectId)
      .withSuccessResponse[Boolean](200)
      .withErrorResponse[GlobalErrorResponse](400)

  /**
   * 当前模板被引用也允许删除模板
   *
   * Expected answers:
   * code 200 : Boolean (查询模板详情成功)
   * code 400 : GlobalErrorResponse (无效的输入参数)
   *
   * @param xProjectId project id, 用于不同project取token.
   * @param templateId
   */
  def deleteJobTemplate(xProjectId: String, templateId: Long): ApiRequest[Boolean] =
    ApiRequest[Boolean](ApiMethods.DELETE, "https://cs.cn-north-1.myhuaweicloud.com/v1.0", "/{X-Project-Id}/job_template/{template_id}", "application/json")
      .withPathParam("X-Project-Id", xProjectId)
      .withPathParam("template_id", templateId)
      .withSuccessResponse[Boolean](200)
      .withErrorResponse[GlobalErrorResponse](400)

  /**
   *
   *
   * Expected answers:
   * code 200 : Seq[JobTemplate] (模板列表查询成功)
   * code 400 : GlobalErrorResponse (无效的输入参数)
   *
   * @param xProjectId project id, 用于不同project取token.
   * @param cursor 作业模板ID
   * @param limit 查询条数限制
   * @param order 查询结果排序, 升序和降序两种可选
   */
  def getJobTemplates(xProjectId: String, cursor: Long, limit: Int, order: String): ApiRequest[Seq[JobTemplate]] =
    ApiRequest[Seq[JobTemplate]](ApiMethods.GET, "https://cs.cn-north-1.myhuaweicloud.com/v1.0", "/{X-Project-Id}/job_templates", "application/json")
      .withQueryParam("cursor", cursor)
      .withQueryParam("limit", limit)
      .withQueryParam("order", order)
      .withPathParam("X-Project-Id", xProjectId)
      .withSuccessResponse[Seq[JobTemplate]](200)
      .withErrorResponse[GlobalErrorResponse](400)


}

