/*
 * CloudStream Service API
 * 实时流计算服（CloudStream Service，简称CS），是运行在华为云上的实时流式大数据分析服务，完全托管的方式让用户无需感知计算集群，只需聚焦于Stream SQL业务，即时执行作业，完全兼容Apache Flink API。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: CloudStream@huawei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huaweicloud.cs.java.v1.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 更新用户配额信息
 */
@ApiModel(description = "更新用户配额信息")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T18:34:48.675+08:00")
public class UpdateUserQuotaRequest {
  @SerializedName("spu_quota")
  private Integer spuQuota = null;

  @SerializedName("clusters")
  private List<Integer> clusters = null;

  public UpdateUserQuotaRequest spuQuota(Integer spuQuota) {
    this.spuQuota = spuQuota;
    return this;
  }

   /**
   * 用户最大SPU配额
   * @return spuQuota
  **/
  @ApiModelProperty(example = "100", value = "用户最大SPU配额")
  public Integer getSpuQuota() {
    return spuQuota;
  }

  public void setSpuQuota(Integer spuQuota) {
    this.spuQuota = spuQuota;
  }

  public UpdateUserQuotaRequest clusters(List<Integer> clusters) {
    this.clusters = clusters;
    return this;
  }

  public UpdateUserQuotaRequest addClustersItem(Integer clustersItem) {
    if (this.clusters == null) {
      this.clusters = new ArrayList<Integer>();
    }
    this.clusters.add(clustersItem);
    return this;
  }

   /**
   * 分配给用户的集群id列表
   * @return clusters
  **/
  @ApiModelProperty(example = "[111,112]", value = "分配给用户的集群id列表")
  public List<Integer> getClusters() {
    return clusters;
  }

  public void setClusters(List<Integer> clusters) {
    this.clusters = clusters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateUserQuotaRequest updateUserQuotaRequest = (UpdateUserQuotaRequest) o;
    return Objects.equals(this.spuQuota, updateUserQuotaRequest.spuQuota) &&
        Objects.equals(this.clusters, updateUserQuotaRequest.clusters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(spuQuota, clusters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateUserQuotaRequest {\n");
    
    sb.append("    spuQuota: ").append(toIndentedString(spuQuota)).append("\n");
    sb.append("    clusters: ").append(toIndentedString(clusters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

