/*
 * CloudStream Service API
 * 实时流计算服（CloudStream Service，简称CS），是运行在华为云上的实时流式大数据分析服务，完全托管的方式让用户无需感知计算集群，只需聚焦于Stream SQL业务，即时执行作业，完全兼容Apache Flink API。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: CloudStream@huawei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huaweicloud.cs.java.v1;

import com.huaweicloud.cs.java.v1.client.ApiException;
import com.huaweicloud.cs.java.v1.model.GlobalErrorResponse;
import com.huaweicloud.cs.java.v1.model.JobTemplate;
import com.huaweicloud.cs.java.v1.model.JobTemplateRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TemplateApi
 */
@Ignore
public class TemplateApiTest {

    private final TemplateApi api = new TemplateApi();

    
    /**
     * create the job template
     *
     * Create on job template from CloudStream Service
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createJobTemplateTest() throws ApiException {
        String xProjectId = null;
        JobTemplateRequest body = null;
        Boolean response = api.createJobTemplate(xProjectId, body);

        // TODO: test validations
    }
    
    /**
     * 删除作业模板
     *
     * 当前模板被引用也允许删除模板
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteJobTemplateTest() throws ApiException {
        String xProjectId = null;
        Long templateId = null;
        Boolean response = api.deleteJobTemplate(xProjectId, templateId);

        // TODO: test validations
    }
    
    /**
     * query CloudStream Service job templates
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getJobTemplatesTest() throws ApiException {
        String xProjectId = null;
        Long cursor = null;
        Integer limit = null;
        String order = null;
        List<JobTemplate> response = api.getJobTemplates(xProjectId, cursor, limit, order);

        // TODO: test validations
    }
    
}
