/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 */
package com.huaweicloud.cs.v1.model

import com.huaweicloud.cs.v1.client.ApiModel

case class ClusterInfo(
  /* 集群ID */
  clusterId: Option[Long],
  /* 集群名称 */
  name: Option[String],
  /* 集群描述 */
  desc: Option[String],
  /* 集群当前状态码 */
  statusCode: Option[Int],
  /* 集群当前状态名称 */
  statusName: Option[String],
  /* 集群当前状态描述 */
  statusDesc: Option[String],
  /* 集群当前所处的Region */
  regionId: Option[String],
  /* 集群已使用SPU配额 */
  spuUsed: Option[Int],
  /* 集群的最大SPU配额 */
  maximumSpuQuota: Option[Int],
  /* 集群状态异常时的错误原因 */
  errorReason: Option[String],
  /* 集群创建时间 */
  createdAt: Option[Long]
) extends ApiModel


