/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package com.huaweicloud.cs.v1.model

import com.huaweicloud.cs.v1.client.ApiModel

case class ClusterInfo(
  /* 集群ID */
  clusterId: Option[Long],
  /* 集群名称 */
  name: Option[String],
  /* 集群描述 */
  desc: Option[String],
  /* 集群当前状态码 */
  statusCode: Option[Int],
  /* 集群当前状态名称 */
  statusName: Option[String],
  /* 集群当前状态描述 */
  statusDesc: Option[String],
  /* 集群当前所处的Region */
  regionId: Option[String],
  /* 集群已使用SPU配额 */
  spuUsed: Option[Int],
  /* 集群的最大SPU配额 */
  maximumSpuQuota: Option[Int],
  /* 集群状态异常时的错误原因 */
  errorReason: Option[String],
  /* 集群创建时间 */
  createdAt: Option[Long]
) extends ApiModel


