/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package com.huaweicloud.cs.v1.model

import com.huaweicloud.cs.v1.client.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class DeleteTemplateResponse (
  /* 模板ID */
  templateId: Option[Long],
  /* 模板删除是否成功 */
  isSuccess: Option[Boolean]
) extends ApiModel


