/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 */
package com.huaweicloud.cs.v1.model

import com.huaweicloud.cs.v1.client.ApiModel

case class GlobalErrorResponse(
  /* 错误消息码 */
  errorId: Option[String],
  /* 错误消息名 */
  errorName: Option[String],
  /* 错误原因 */
  errorCause: Option[String],
  /* 针对错误的建议 */
  errorSuggestion: Option[String],
  /* 扩展信息, JSON格式 */
  errorJsonOpt: Option[String],
  /* 错误发生的时间, 毫秒数 */
  errorTime: Option[Long]
) extends ApiModel


