/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package com.huaweicloud.cs.v1.model

import com.huaweicloud.cs.v1.client.ApiModel

case class JobOverviewEntity(
  /* 作业总数 */
  totalJobs: Option[Int],
  /* 运行的作业总数 */
  runningJobsCount: Option[Int],
  /* 已完成的作业总数 */
  finishedJobCount: Option[Int],
  /* 运行异常的作业总数 */
  exceptionJobCount: Option[Int],
  /* 正在运行的作业总费用 */
  runningJobCharge: Option[Int],
  /* 正在运行的作业单价合计 */
  runningJobPrice: Option[Int],
  /* 正在运行的作业消耗SPU总数 */
  runningJobTotalSpu: Option[Int],
  /* 正在运行的作业总时长 */
  runningJobTotalTime: Option[Int],
  /* 结算币种 */
  billingUnit: Option[JobOverviewEntityEnums.BillingUnit],
  /* 时间单位 */
  timeUnit: Option[JobOverviewEntityEnums.TimeUnit]
) extends ApiModel

object JobOverviewEntityEnums {

  type BillingUnit = BillingUnit.Value
  type TimeUnit = TimeUnit.Value

  object BillingUnit extends Enumeration {
    val CNY = Value("CNY")
    val HKD = Value("HKD")
    val EUR = Value("EUR")
    val DEM = Value("DEM")
    val USD = Value("USD")
  }

  object TimeUnit extends Enumeration {
    val HOUR = Value("HOUR")
  }

}

