/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package com.huaweicloud.cs.v1.model

import com.huaweicloud.cs.v1.client.ApiModel

case class OverviewEntity(
  /* 总费用 */
  totalPrice: Option[Int],
  jobOverview: Option[JobOverviewEntity],
  clusterOverview: Option[ClusterOverviewEntity]
) extends ApiModel


